package View;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author PC
 */
import com.formdev.flatlaf.FlatLightLaf;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.sql.SQLException;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
public class DangNhapUI extends javax.swing.JFrame {

    /**
     * Creates new form DangNhapUI
     */
    HashMap<String, String[]> accounts = new HashMap<>();

    public DangNhapUI() {
        initComponents();
         fakeData(); // gọi hàm khởi tạo tài khoản giả
         loadRememberedAccount();
         
    }
    private void loadRememberedAccount() {
    File f = new File("remember.txt");
    if (f.exists()) {
        try (BufferedReader br = new BufferedReader(new FileReader(f))) {
            txt_tendangnhap.setText(br.readLine());
            pass.setText(br.readLine());
            check_ghinhodangnhap.setSelected(true);
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }
}

    // ✅ Tạo tài khoản giả
    private void fakeData() {
        accounts.put("admin", new String[]{"123", "Admin"});
        accounts.put("nv01", new String[]{"456", "Nhân viên"});
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btn_lammoi = new javax.swing.JButton();
        btn_thoat = new javax.swing.JButton();
        btn_quenmatkhau = new javax.swing.JButton();
        btn_dangnhap = new javax.swing.JButton();
        pass = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        txt_tendangnhap = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        check_ghinhodangnhap = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        cb_Role = new javax.swing.JComboBox<>();

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/o (1).png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 204, 204));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("UTM Conestoga", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 102, 102));
        jLabel3.setText("ĐĂNG NHẬP HỆ THỐNG ");
        jPanel7.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, 270, 40));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/lintinh/o (1).png"))); // NOI18N
        jPanel7.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-120, 0, 750, 160));

        getContentPane().add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 160));

        jPanel1.setBackground(new java.awt.Color(255, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_lammoi.setForeground(new java.awt.Color(51, 51, 0));
        btn_lammoi.setText("ReSet");
        btn_lammoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lammoiActionPerformed(evt);
            }
        });
        jPanel1.add(btn_lammoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, -1, -1));

        btn_thoat.setBackground(new java.awt.Color(255, 0, 51));
        btn_thoat.setForeground(new java.awt.Color(255, 255, 255));
        btn_thoat.setText("Thoát");
        btn_thoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_thoatActionPerformed(evt);
            }
        });
        jPanel1.add(btn_thoat, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 260, -1, -1));

        btn_quenmatkhau.setBackground(new java.awt.Color(51, 51, 255));
        btn_quenmatkhau.setForeground(new java.awt.Color(255, 255, 255));
        btn_quenmatkhau.setText("QUÊN MẬT KHẨU ");
        btn_quenmatkhau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_quenmatkhauActionPerformed(evt);
            }
        });
        jPanel1.add(btn_quenmatkhau, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 220, 240, -1));

        btn_dangnhap.setBackground(new java.awt.Color(204, 51, 102));
        btn_dangnhap.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        btn_dangnhap.setForeground(new java.awt.Color(255, 255, 255));
        btn_dangnhap.setText("ĐĂNG NHẬP");
        btn_dangnhap.setBorderPainted(false);
        btn_dangnhap.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_dangnhap.setFocusPainted(false);
        btn_dangnhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dangnhapActionPerformed(evt);
            }
        });
        jPanel1.add(btn_dangnhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 240, -1));
        jPanel1.add(pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 220, -1));

        jLabel5.setForeground(new java.awt.Color(255, 0, 102));
        jLabel5.setText("MẬT KHẨU");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, -1, -1));
        jPanel1.add(txt_tendangnhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 220, -1));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setForeground(new java.awt.Color(255, 51, 153));
        jLabel1.setText("TÊN ĐĂNG NHẬP");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 70, -1, 20));

        check_ghinhodangnhap.setText("Ghi nhớ đăng nhập");
        check_ghinhodangnhap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                check_ghinhodangnhapActionPerformed(evt);
            }
        });
        jPanel1.add(check_ghinhodangnhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 180, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 51, 204));
        jLabel6.setText("Chọn quyền đăng nhập");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, -1, 30));

        cb_Role.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Admin", "Nhân Viên" }));
        jPanel1.add(cb_Role, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 180, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 630, 350));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void check_ghinhodangnhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_check_ghinhodangnhapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_check_ghinhodangnhapActionPerformed

    private void btn_dangnhapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dangnhapActionPerformed
       
        String username = txt_tendangnhap.getText();
        String password = String.valueOf(pass.getPassword());
        String selectedRole = cb_Role.getSelectedItem().toString();

        if (accounts.containsKey(username)) {
        String[] info = accounts.get(username);
        String pass = info[0];
        String role = info[1];
    
    if (password.equals(pass) && role.equals(selectedRole)) {
        if (role.equals("Admin")) {
            try {
                new  FromAdmin().setVisible(true);
            } catch (SQLException ex) {
                Logger.getLogger(DangNhapUI.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            new FromNhanVien().setVisible(true);
        }
        dispose(); // đóng form đăng nhập
    } else {
        JOptionPane.showMessageDialog(this, "Sai mật khẩu hoặc sai quyền!");
    }
} else {
    JOptionPane.showMessageDialog(this, "Tài khoản không tồn tại!");
}
      

           if (check_ghinhodangnhap.isSelected()) {
    try (FileWriter fw = new FileWriter("remember.txt")) {
        fw.write(username + "\n" + password);
    } catch (IOException ex) {
        ex.printStackTrace();
    }
} else {
    // Nếu không chọn thì xóa file (nếu có)
    File f = new File("remember.txt");
    if (f.exists()) f.delete();
}



    }//GEN-LAST:event_btn_dangnhapActionPerformed

    private void btn_quenmatkhauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_quenmatkhauActionPerformed
        // TODO add your handling code here:
        String username = txt_tendangnhap.getText();

if (accounts.containsKey(username)) {
    String[] info = accounts.get(username);
    String password = info[0];

    JOptionPane.showMessageDialog(this,
        "Mật khẩu của bạn là: " + password,
        "Quên mật khẩu",
        JOptionPane.INFORMATION_MESSAGE);
} else {
    JOptionPane.showMessageDialog(this,
        "Không tìm thấy tài khoản!",
        "Lỗi",
        JOptionPane.ERROR_MESSAGE);
}

    }//GEN-LAST:event_btn_quenmatkhauActionPerformed

    private void btn_lammoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lammoiActionPerformed
        // TODO add your handling code here:
        txt_tendangnhap.setText("");
        pass.setText("");
        check_ghinhodangnhap.setSelected(false);
    }//GEN-LAST:event_btn_lammoiActionPerformed

    private void btn_thoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_thoatActionPerformed
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(this,
            "Bạn có chắc chắn muốn thoát?",
            "Xác nhận thoát",
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE);

    if (confirm == JOptionPane.YES_OPTION) {
        System.exit(0); // Thoát chương trình
    }
    }//GEN-LAST:event_btn_thoatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DangNhapUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DangNhapUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DangNhapUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DangNhapUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                 try {
          UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (Exception ex) {
            ex.printStackTrace();
        }

       
    
                new DangNhapUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_dangnhap;
    private javax.swing.JButton btn_lammoi;
    private javax.swing.JButton btn_quenmatkhau;
    private javax.swing.JButton btn_thoat;
    private javax.swing.JComboBox<String> cb_Role;
    private javax.swing.JCheckBox check_ghinhodangnhap;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPasswordField pass;
    private javax.swing.JTextField txt_tendangnhap;
    // End of variables declaration//GEN-END:variables
}
