package View;


import com.formdev.flatlaf.FlatLightLaf;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Cursor;
import java.awt.Image;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.SQLException;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JPanel;
import javax.swing.UIManager;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author PC
 */
public class FromAdmin extends javax.swing.JFrame {

    /**
     * Creates new form FromAdmin
     */private CardLayout cardLayout;
     private Home panelHome;  // 👈 Khai báo biến JPanel kiểu Home
     private quanlynhanvien panelquanlynhanvien; 
     private quanlysanpham panelquanlysanpham; 
     private quanlybanhang panelquanlybanhang; 
     private quanlykhachhang panelquanlykhachhang; 
     private quanlychitiethoadon panelquanlychitiethoadon;

    public FromAdmin() throws SQLException {
        initComponents();
        cardLayout = (CardLayout) panel_content.getLayout(); // lưu lại layout
     panelHome = new Home();
     panelquanlynhanvien = new quanlynhanvien();
     panelquanlysanpham = new quanlysanpham();
     //panelquanlybanhang = new quanlybanhang();
    panelquanlybanhang = new quanlybanhang(cardLayout, panel_content);

     panelquanlychitiethoadon = new quanlychitiethoadon(cardLayout, panel_content); // truyền đúng
     
    JPanel blankPanel = new JPanel(); 
   
    // panelquanlybanhang = new quanlybanhang(cardLayout, panel_content);
    panel_content.add(blankPanel, "blank");
    panel_content.add(panelHome, "home");
    panel_content.add(panelquanlynhanvien,"qlnhanvien");
    panel_content.add(panelquanlysanpham,"qlsanpham");
    panel_content.add(panelquanlybanhang,"qlbanhang");
   // panel_content.add(panelquanlykhachhang,"qlkhachhang");
    panel_content.add(panelquanlychitiethoadon,"qlchitiethoadon");
    
    // Nếu bạn muốn ẩn ban đầu thì KHÔNG gọi show
    // Nếu muốn hiện luôn thì gọi:
    // cardLayout.show(panel_content, "home");

    getContentPane().setBackground(new Color(255, 255, 255));
    //cardLayout = (CardLayout) panel_content.getLayout();
     cardLayout.show(panel_content, "blank");

     
        
        
    }
    
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        panel_menu = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        lb_hoadon = new javax.swing.JLabel();
        lb_home = new javax.swing.JLabel();
        lb_qlnhanvien = new javax.swing.JLabel();
        lb_chitiethoadon = new javax.swing.JLabel();
        lb_qlsanpham = new javax.swing.JLabel();
        lb_quanlykhachhang = new javax.swing.JLabel();
        lb_thongke = new javax.swing.JLabel();
        lb_qlkhachhang = new javax.swing.JLabel();
        lb_dangxuat = new javax.swing.JLabel();
        lb_quanlytaikhoan1 = new javax.swing.JLabel();
        panel_content = new javax.swing.JPanel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(264, 0, -1, 560));

        panel_menu.setBackground(new java.awt.Color(255, 204, 204));
        panel_menu.setPreferredSize(new java.awt.Dimension(230, 500));
        panel_menu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panel_menu.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 246, -1, -1));

        lb_hoadon.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lb_hoadon.setForeground(new java.awt.Color(204, 0, 255));
        lb_hoadon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-file-128.png"))); // NOI18N
        lb_hoadon.setText("          QUẢN LÝ HÓA ĐƠN");
        lb_hoadon.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lb_hoadon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_hoadonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lb_hoadonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lb_hoadonMouseExited(evt);
            }
        });
        panel_menu.add(lb_hoadon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 240, 60));

        lb_home.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lb_home.setForeground(new java.awt.Color(204, 0, 255));
        lb_home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-home-48.png"))); // NOI18N
        lb_home.setText("                   HOME");
        lb_home.setToolTipText("");
        lb_home.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lb_home.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lb_home.setIconTextGap(1);
        lb_home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_homeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lb_homeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lb_homeMouseExited(evt);
            }
        });
        panel_menu.add(lb_home, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 80));

        lb_qlnhanvien.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lb_qlnhanvien.setForeground(new java.awt.Color(204, 0, 255));
        lb_qlnhanvien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-users-48.png"))); // NOI18N
        lb_qlnhanvien.setText("        QUẢN LÝ NHÂN VIÊN");
        lb_qlnhanvien.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lb_qlnhanvien.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lb_qlnhanvien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_qlnhanvienMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lb_qlnhanvienMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lb_qlnhanvienMouseExited(evt);
            }
        });
        panel_menu.add(lb_qlnhanvien, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 240, 60));

        lb_chitiethoadon.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lb_chitiethoadon.setForeground(new java.awt.Color(204, 0, 204));
        lb_chitiethoadon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-bill-100.png"))); // NOI18N
        lb_chitiethoadon.setText("        CHI TIẾT HÓA ĐƠN");
        lb_chitiethoadon.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panel_menu.add(lb_chitiethoadon, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 240, 60));

        lb_qlsanpham.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lb_qlsanpham.setForeground(new java.awt.Color(204, 0, 204));
        lb_qlsanpham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-box-50.png"))); // NOI18N
        lb_qlsanpham.setText("         QUẢN LÝ SẢN PHẨM");
        lb_qlsanpham.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lb_qlsanpham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lb_qlsanphamMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lb_qlsanphamMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lb_qlsanphamMouseExited(evt);
            }
        });
        panel_menu.add(lb_qlsanpham, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 240, 60));

        lb_quanlykhachhang.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lb_quanlykhachhang.setForeground(new java.awt.Color(204, 0, 204));
        lb_quanlykhachhang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-user-48.png"))); // NOI18N
        lb_quanlykhachhang.setText("          QUẢN LÝ NHÀ CUNG CẤP");
        lb_quanlykhachhang.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panel_menu.add(lb_quanlykhachhang, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 240, 60));

        lb_thongke.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lb_thongke.setForeground(new java.awt.Color(204, 0, 204));
        lb_thongke.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-combo-chart-100.png"))); // NOI18N
        lb_thongke.setText("          THỐNG KÊ");
        lb_thongke.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panel_menu.add(lb_thongke, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 440, 240, 60));

        lb_qlkhachhang.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lb_qlkhachhang.setForeground(new java.awt.Color(204, 0, 204));
        lb_qlkhachhang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-users-48.png"))); // NOI18N
        lb_qlkhachhang.setText("           QUẢN LÝ KHÁCH HÀNG");
        lb_qlkhachhang.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panel_menu.add(lb_qlkhachhang, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 240, 60));

        lb_dangxuat.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lb_dangxuat.setForeground(new java.awt.Color(204, 0, 204));
        lb_dangxuat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-logout-32.png"))); // NOI18N
        lb_dangxuat.setText("                ĐĂNG XUẤT");
        lb_dangxuat.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panel_menu.add(lb_dangxuat, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 560, 240, 100));

        lb_quanlytaikhoan1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lb_quanlytaikhoan1.setForeground(new java.awt.Color(204, 0, 204));
        lb_quanlytaikhoan1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-user-24.png"))); // NOI18N
        lb_quanlytaikhoan1.setText("           QUẢN LÝ TÀI KHOẢN");
        lb_quanlytaikhoan1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panel_menu.add(lb_quanlytaikhoan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 500, 240, 60));

        getContentPane().add(panel_menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 660));

        panel_content.setLayout(new java.awt.CardLayout());
        getContentPane().add(panel_content, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 960, 630));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void lb_homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_homeMouseClicked
        // TODO add your handling code here:
          cardLayout.show(panel_content, "home");
           lb_home.setBackground(new java.awt.Color(255, 102, 102));
           lb_home.setOpaque(true);

            resetMenuColorsExcept(lb_home);
    }//GEN-LAST:event_lb_homeMouseClicked

    private void lb_homeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_homeMouseEntered
        // TODO add your handling code here:
         lb_home.setBackground(new java.awt.Color(255, 153, 153));
    lb_home.setOpaque(true);
    }//GEN-LAST:event_lb_homeMouseEntered

    private void lb_homeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_homeMouseExited
        // TODO add your handling code here:
        lb_home.setBackground(null);
    lb_home.setOpaque(false);
    }//GEN-LAST:event_lb_homeMouseExited

    private void lb_qlnhanvienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_qlnhanvienMouseClicked
        // TODO add your handling code here:
         cardLayout.show(panel_content, "qlnhanvien");
           lb_qlnhanvien.setBackground(new java.awt.Color(255, 102, 102));
           lb_qlnhanvien.setOpaque(true);

                resetMenuColorsExcept(lb_qlnhanvien);
    }//GEN-LAST:event_lb_qlnhanvienMouseClicked

    private void lb_qlnhanvienMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_qlnhanvienMouseEntered
        // TODO add your handling code here:
          lb_qlnhanvien.setBackground(new java.awt.Color(255, 153, 153));
    lb_qlnhanvien.setOpaque(true);
    }//GEN-LAST:event_lb_qlnhanvienMouseEntered

    private void lb_qlnhanvienMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_qlnhanvienMouseExited
        // TODO add your handling code here:
         lb_qlnhanvien.setBackground(new java.awt.Color(255, 153, 153));
         lb_qlnhanvien.setOpaque(true);
    }//GEN-LAST:event_lb_qlnhanvienMouseExited

    private void lb_qlsanphamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_qlsanphamMouseClicked
        // TODO add your handling code here:
         cardLayout.show(panel_content, "qlsanpham");
           lb_qlsanpham.setBackground(new java.awt.Color(255, 102, 102));
           lb_qlsanpham.setOpaque(true);

                resetMenuColorsExcept(lb_qlsanpham);
    }//GEN-LAST:event_lb_qlsanphamMouseClicked

    private void lb_qlsanphamMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_qlsanphamMouseEntered
        // TODO add your handling code here:
           lb_qlsanpham.setBackground(new java.awt.Color(255, 153, 153));
           lb_qlsanpham.setOpaque(true);
    }//GEN-LAST:event_lb_qlsanphamMouseEntered

    private void lb_qlsanphamMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_qlsanphamMouseExited
        // TODO add your handling code here:
         lb_qlsanpham.setBackground(new java.awt.Color(255, 153, 153));
         lb_qlsanpham.setOpaque(true);
        
    }//GEN-LAST:event_lb_qlsanphamMouseExited

    private void lb_hoadonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_hoadonMouseClicked
        // TODO add your handling code here:
         cardLayout.show(panel_content, "qlbanhang");
           lb_hoadon.setBackground(new java.awt.Color(255, 102, 102));
           lb_hoadon.setOpaque(true);

                resetMenuColorsExcept(lb_hoadon);
    }//GEN-LAST:event_lb_hoadonMouseClicked

    private void lb_hoadonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_hoadonMouseEntered
        // TODO add your handling code here:
         lb_hoadon.setBackground(new java.awt.Color(255, 153, 153));
           lb_hoadon.setOpaque(true);
    }//GEN-LAST:event_lb_hoadonMouseEntered

    private void lb_hoadonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lb_hoadonMouseExited
        // TODO add your handling code here:
          lb_hoadon.setBackground(new java.awt.Color(255, 153, 153));
         lb_hoadon.setOpaque(true);
    }//GEN-LAST:event_lb_hoadonMouseExited
private void resetMenuColorsExcept(javax.swing.JLabel selectedLabel) {
    javax.swing.JLabel[] menuLabels = {
        lb_home, lb_hoadon, lb_qlnhanvien,
        lb_chitiethoadon, lb_qlsanpham,
        lb_quanlykhachhang, lb_thongke, lb_qlkhachhang, lb_dangxuat
    };

    for (javax.swing.JLabel label : menuLabels) {
        if (label != selectedLabel) {
            label.setBackground(null);
            label.setOpaque(false);
        }
    }
}

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FromAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FromAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FromAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FromAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() { 
                 try {
            UIManager.setLookAndFeel(new FlatLightLaf());
        } catch (Exception ex) {
            ex.printStackTrace();
        }

     
                try {
                    new FromAdmin().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(FromAdmin.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lb_chitiethoadon;
    private javax.swing.JLabel lb_dangxuat;
    private javax.swing.JLabel lb_hoadon;
    private javax.swing.JLabel lb_home;
    private javax.swing.JLabel lb_qlkhachhang;
    private javax.swing.JLabel lb_qlnhanvien;
    private javax.swing.JLabel lb_qlsanpham;
    private javax.swing.JLabel lb_quanlykhachhang;
    private javax.swing.JLabel lb_quanlytaikhoan1;
    private javax.swing.JLabel lb_thongke;
    private javax.swing.JPanel panel_content;
    private javax.swing.JPanel panel_menu;
    // End of variables declaration//GEN-END:variables
}

