package View;


import Controller.DAO;
import java.awt.Image;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.ImageIcon;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */

/**
 *
 * @author PC
 */
public class Home extends javax.swing.JPanel {

    /**
     * Creates new form Home
     */
    public Home() throws SQLException {
        initComponents();
          ImageIcon icon = new ImageIcon("src/Image/anh.jpg");
        Image scaledImage = icon.getImage().getScaledInstance(100, 90, Image.SCALE_SMOOTH);
        lb_anh.setIcon(new ImageIcon(scaledImage));

        LocalDateTime now = LocalDateTime.now();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("HH:mm - dd/MM/yyyy");
        String gioDangNhap = now.format(formatter);

             lblThoiGianDangNhap.setText("Đăng nhập lúc: " + gioDangNhap);
             hienThiSanPhamVuotTonKho() ;
             hienThiSanPhamBanChay();
             hienthispmoi();
               DAO dao = new DAO();
             lbnhacungcap.setText("Có " + dao.demNhaCungCap() + " nhà cung cấp");
             lbspdangban.setText("" +dao.demSanPhamDangBan());
             lbhoadon.setText("Đã bán: " + dao.demHoaDonHomNay());
             lbdoanhthu.setText(" " + dao.tinhDoanhThuHomNay() + " VNĐ");

           
    }
     private void hienThiSanPhamVuotTonKho() throws SQLException {
        DAO dao = new DAO();
        List<String> spVuot = dao.getDanhSachSanPhamVuotTonKho();

        if (spVuot.isEmpty()) {
           lb_sptonkho.setText("Không có sản phẩm vượt tồn kho");
        } else {
            StringBuilder sb = new StringBuilder();
            for (String ten : spVuot) {
                sb.append("- ").append(ten).append("\n");
            }
            lb_sptonkho.setText("<html>" + sb.toString().replace("\n", "<br>") + "</html>");
        }
    }
     
     private void hienThiSanPhamBanChay() {
          DAO dao = new DAO();
        List<String> spBanChay = dao.getSanPhamBanChay();

        if (spBanChay.isEmpty()) {
            lb_spbanchay.setText("Không có dữ liệu");
        } else {
            StringBuilder sb = new StringBuilder();
            for (String ten : spBanChay) {
                sb.append("- ").append(ten).append("\n");
            }
           lb_spbanchay.setText("<html>" + sb.toString().replace("\n", "<br>") + "</html>");
        }
    }
     private void hienthispmoi(){
   DAO dao = new DAO();
    List<String> spMoi = dao.getSanPhamMoi();

        if (spMoi.isEmpty()) {
    lb_spmoi.setText("Không có sản phẩm mới");
        } else {
    StringBuilder sb = new StringBuilder();
    for (String sp : spMoi) {
        sb.append("- ").append(sp).append("\n");
    }
    lb_spmoi.setText("<html>" + sb.toString().replace("\n", "<br>") + "</html>");
}
     }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_content = new javax.swing.JPanel();
        panelHome = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lblThoiGianDangNhap = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        lbhoadon = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        lbdoanhthu = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        lbnhacungcap = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        lbspdangban = new javax.swing.JLabel();
        lbsphamdangban = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        lb_anh = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lb_sptonkho = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        lb_spbanchay = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lb_spmoi = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        panel_content.setLayout(new java.awt.CardLayout());

        panelHome.setBackground(new java.awt.Color(204, 204, 204));
        panelHome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 153)));
        panelHome.setPreferredSize(new java.awt.Dimension(850, 500));
        panelHome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setForeground(new java.awt.Color(0, 204, 153));
        jLabel3.setText("Chủ cửa hàng ");
        panelHome.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, -1, -1));

        lblThoiGianDangNhap.setText("Thời gian đăng nhập:");
        panelHome.add(lblThoiGianDangNhap, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 70, -1, -1));

        jLabel5.setText("|");
        panelHome.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, -1, -1));

        jLabel7.setText("Chức vụ:");
        panelHome.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 70, -1, -1));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-bill-50.png"))); // NOI18N
        jPanel4.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        jLabel19.setText("Hóa đơn hôm nay");
        jPanel4.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        lbhoadon.setText("Đã bán :");
        jPanel4.add(lbhoadon, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, -1, -1));

        panelHome.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 310, 180, 190));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-speaker-64.png"))); // NOI18N
        jLabel4.setText("Thông Báo Hệ Thống");
        panelHome.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 210, 30));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-dollar-bag-50.png"))); // NOI18N
        jPanel6.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        jLabel22.setText("Doanh Thu trong ngày");
        jPanel6.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        lbdoanhthu.setText("Thống kê doanh thu");
        jPanel6.add(lbdoanhthu, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 90, 40));

        panelHome.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 310, 190, 190));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-users-30.png"))); // NOI18N
        jLabel13.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lbnhacungcap.setText("Nhà Cung cấp");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbnhacungcap))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(lbnhacungcap)
                .addContainerGap(66, Short.MAX_VALUE))
        );

        panelHome.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 190, 190));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbspdangban.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbspdangban.setForeground(new java.awt.Color(255, 153, 51));
        lbspdangban.setText("Sản phẩm ");
        jPanel7.add(lbspdangban, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 90, 20));

        lbsphamdangban.setText("Sản phẩm đang bán");
        jPanel7.add(lbsphamdangban, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 110, 40));

        panelHome.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, 180, 190));

        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font(".VnArial", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 102, 102));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-waving-hand-light-skin-tone-48.png"))); // NOI18N
        jLabel2.setText("XIN CHAO ADMIN , Nguyen Van A");
        jPanel8.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));
        jPanel8.add(lb_anh, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 0, 120, 110));

        panelHome.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 810, 110));

        jLabel9.setText("* Sản phẩm vượt ngưỡng tồn kho: ");
        panelHome.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        lb_sptonkho.setText("Tồn kho:");
        panelHome.add(lb_sptonkho, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, -1, -1));

        jLabel10.setText("* Sản phẩm bán chạy trong ngày :");
        panelHome.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, -1, -1));

        lb_spbanchay.setText("bán chạy: ");
        panelHome.add(lb_spbanchay, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, -1, -1));

        jLabel11.setText("* Sản phẩm mới:");
        panelHome.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 150, -1, -1));

        lb_spmoi.setText("0 co sp moi");
        panelHome.add(lb_spmoi, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 150, -1, -1));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icons8-combo-chart-50.png"))); // NOI18N
        jLabel12.setText("THỐNG KÊ NHANH ");
        jLabel12.setToolTipText("");
        jLabel12.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jLabel12.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel12.setIconTextGap(50);
        panelHome.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 280, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelHome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1033, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 516, Short.MAX_VALUE)
                    .addComponent(panel_content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 517, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelHome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 616, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 78, Short.MAX_VALUE)
                    .addComponent(panel_content, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 78, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JLabel lb_anh;
    private javax.swing.JLabel lb_spbanchay;
    private javax.swing.JLabel lb_spmoi;
    private javax.swing.JLabel lb_sptonkho;
    private javax.swing.JLabel lbdoanhthu;
    private javax.swing.JLabel lbhoadon;
    private javax.swing.JLabel lblThoiGianDangNhap;
    private javax.swing.JLabel lbnhacungcap;
    private javax.swing.JLabel lbspdangban;
    private javax.swing.JLabel lbsphamdangban;
    private javax.swing.JPanel panelHome;
    private javax.swing.JPanel panel_content;
    // End of variables declaration//GEN-END:variables
}
