/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View;

import Controller.ChiTietHoaDonDAO;
import Controller.GradientPanel;
import Controller.HoaDonDAO;
import Controller.JDialogChiTietHoaDon;
import Controller.JDialogThemHoaDon;
import Controller.RoundedTextField;
import Controller.SanPhamDao;
import Controller.panelvien;
import Model.ChiTietHoaDon;
import Model.HoaDon;
import View.quanlychitiethoadon;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.math.BigDecimal;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import javax.swing.SwingConstants;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PC
 */
public class quanlybanhang extends javax.swing.JPanel {

    /**
     * Creates new form quanlybanhang
     */
    SanPhamDao spDao = new SanPhamDao();
     ChiTietHoaDonDAO ctDao = new ChiTietHoaDonDAO();
     HoaDonDAO hdDao = new HoaDonDAO(); // ✅ thêm dòng này
     private CardLayout cardLayout;
   private JPanel panelContent;
    public quanlybanhang(CardLayout cardLayout, JPanel panelContent) {
        initComponents();
        this.cardLayout = cardLayout;
    this.panelContent = panelContent;
    
        loadTableHoaDon(); 
        tbhoadon.addMouseListener(new MouseAdapter() {
    public void mouseClicked(MouseEvent evt) {
        tbhoadonMouseClicked(evt);
    }
});
        tbhoadon.setDefaultEditor(Object.class, null);
         canGiuaTable();
         tbhoadon.getTableHeader().setFont(new java.awt.Font("Segoe UI", Font.BOLD, 15));

// Placeholder cho các TextField
        setPlaceholder(txtMaHD, "Mã HĐ");
        setPlaceholder(txtkhachhang, "Mã KH");
        setPlaceholder(txtTongTien, "Tổng tiền (tự động)");
        setPlaceholder(txttimkiem, "Nhập mã hoặc tên KH để tìm...");
    
     
     
    
    }
    private void setPlaceholder(JTextField txt, String text) {
    txt.setText(text);
    txt.setForeground(Color.GRAY);

    txt.addFocusListener(new java.awt.event.FocusAdapter() {
        public void focusGained(java.awt.event.FocusEvent evt) {
            if (txt.getText().equals(text)) {
                txt.setText("");
                txt.setForeground(Color.BLACK);
            }
        }

        public void focusLost(java.awt.event.FocusEvent evt) {
            if (txt.getText().isEmpty()) {
                txt.setText(text);
                txt.setForeground(Color.GRAY);
            }
        }
    });
}

    public void canGiuaTable() {
    DefaultTableCellRenderer renderer = new DefaultTableCellRenderer();
    renderer.setHorizontalAlignment(SwingConstants.CENTER);
    tbhoadon.setShowGrid(true); // Hiển thị lưới
    tbhoadon.setGridColor(Color.GRAY); // Màu viền

    renderer.setForeground(new Color(0, 0, 0)); // 🎨 Màu chữ hồng đậm

for (int i = 0; i < tbhoadon.getColumnCount(); i++) {
    tbhoadon.getColumnModel().getColumn(i).setCellRenderer(renderer);
}

}
   
    public void loadTableHoaDon() {
    DefaultTableModel model = (DefaultTableModel) tbhoadon.getModel();
    model.setRowCount(0); // Xóa dữ liệu cũ

    List<HoaDon> danhSach = new HoaDonDAO().getAllHoaDon(); // Gọi DAO lấy dữ liệu
    SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");

    for (HoaDon hd : danhSach) {
        Object[] row = new Object[] {
            hd.getMaHD(),
            sdf.format(hd.getNgayLap()), // Hiển thị ngày định dạng yyyy-MM-dd
            hd.getMaKH(),
            hd.getTongTien()
        };
        model.addRow(row);
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new GradientPanel()
        ;
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new panelvien(20, new Color(243, 244, 246));
        ;
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lbdoituong = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        NgayLap = new com.toedter.calendar.JDateChooser();
        txtMaHD = new RoundedTextField(20);
        txtTongTien = new RoundedTextField(20);
        bt_them = new javax.swing.JButton();
        bt_xoa = new javax.swing.JButton();
        bt_capnhat = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txttimkiem = new javax.swing.JTextField();
        txtkhachhang = new RoundedTextField(20);
        btn_chitiethoadon = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbhoadon = new javax.swing.JTable();

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText(" ");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icon/icons8-bill-80.png"))); // NOI18N
        jLabel2.setText("QUẢN LÝ HÓA ĐƠN MỸ PHẨM ");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, -1, -1));

        jPanel3.setBackground(new java.awt.Color(243, 238, 232));

        jLabel4.setText("Mã Hóa Đơn");

        jLabel5.setText("Ngày Lập ");

        lbdoituong.setText("Mã Khách Hàng");

        jLabel7.setText("Tổng Tiền");

        txtTongTien.setEditable(false);

        bt_them.setBackground(new java.awt.Color(34, 197, 94));
        bt_them.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        bt_them.setForeground(new java.awt.Color(255, 255, 255));
        bt_them.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icon/plus-math.png"))); // NOI18N
        bt_them.setText("Thêm ");
        bt_them.setIconTextGap(5);
        bt_them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_themActionPerformed(evt);
            }
        });

        bt_xoa.setBackground(new java.awt.Color(239, 68, 68));
        bt_xoa.setForeground(new java.awt.Color(255, 255, 255));
        bt_xoa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icon/delete.png"))); // NOI18N
        bt_xoa.setText("Xóa ");
        bt_xoa.setIconTextGap(5);
        bt_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_xoaActionPerformed(evt);
            }
        });

        bt_capnhat.setBackground(new java.awt.Color(251, 191, 36));
        bt_capnhat.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        bt_capnhat.setForeground(new java.awt.Color(255, 255, 255));
        bt_capnhat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icon/edit.png"))); // NOI18N
        bt_capnhat.setText("Sửa");
        bt_capnhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_capnhatActionPerformed(evt);
            }
        });

        jLabel3.setText("Tìm Kiếm Hóa đơn");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NgayLap, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel4))
                        .addGap(76, 76, 76)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbdoituong)
                            .addComponent(txtkhachhang, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(bt_them)
                                .addGap(18, 18, 18)
                                .addComponent(bt_capnhat)
                                .addGap(18, 18, 18)
                                .addComponent(bt_xoa))
                            .addComponent(txttimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 298, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(36, 36, 36))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtMaHD, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jLabel4))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbdoituong)
                            .addComponent(jLabel3))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 5, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(bt_them, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt_capnhat, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bt_xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(txtMaHD, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtkhachhang)
                                .addComponent(txttimkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(NgayLap, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(20, 20, 20))
        );

        btn_chitiethoadon.setBackground(new java.awt.Color(130, 102, 255));
        btn_chitiethoadon.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_chitiethoadon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icon/icons8-list-64.png"))); // NOI18N
        btn_chitiethoadon.setText("Chi tiết hóa đơn");
        btn_chitiethoadon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_chitiethoadonActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(20, 153, 255));
        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/icon/export.png"))); // NOI18N
        jButton2.setText("Xuất Excel");

        tbhoadon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã Hóa Đơn", "Ngày Lập", "Mã Khách Hàng", "Tổng Tiền"
            }
        ));
        tbhoadon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbhoadonMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbhoadon);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(btn_chitiethoadon, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(27, 27, 27)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(115, 115, 115))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 814, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(28, 28, 28)))
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_chitiethoadon, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bt_themActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_themActionPerformed
        // TODO add your handling code here:
    // Mở dialog thêm hóa đơn
    JDialogThemHoaDon dialog = new JDialogThemHoaDon(null);
    dialog.setLocationRelativeTo(this);
    dialog.setVisible(true);

    // Sau khi dialog đóng, load lại bảng hóa đơn
    loadTableHoaDon();
    }//GEN-LAST:event_bt_themActionPerformed

    private void bt_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_xoaActionPerformed
        // TODO add your handling code here:
        int selectedRow = tbhoadon.getSelectedRow();
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Vui lòng chọn hóa đơn cần xóa!");
        return;
    }

    String maHD = tbhoadon.getValueAt(selectedRow, 0).toString();

    int confirm = JOptionPane.showConfirmDialog(this, 
        "Bạn có chắc chắn muốn xóa hóa đơn " + maHD + " không?", 
        "Xác nhận xóa", 
        JOptionPane.YES_NO_OPTION);

    if (confirm == JOptionPane.YES_OPTION) {
        try {
            // 1. Xóa chi tiết hóa đơn trước
            ctDao.deleteChiTietByMaHD(maHD);

            // 2. Xóa hóa đơn
            hdDao.deleteHoaDon(maHD);

            JOptionPane.showMessageDialog(this, "Xóa hóa đơn thành công!");
            loadTableHoaDon(); // Load lại bảng
        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Xóa thất bại: " + e.getMessage());
        }
    }

    }//GEN-LAST:event_bt_xoaActionPerformed

    private void suaHoaDon() {
    int selectedRow = tbhoadon.getSelectedRow();
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Vui lòng chọn hóa đơn cần sửa!");
        return;
    }

    String oldMaHD = tbhoadon.getValueAt(selectedRow, 0).toString(); // Mã cũ
    String newMaHD = txtMaHD.getText().trim();
  String maKH = txtkhachhang.getText();

if (maKH == null || maKH.trim().isEmpty() || 
    maKH.trim().equals("Mã KH") || txtkhachhang.getForeground().equals(Color.GRAY)) {
    maKH = null;
} else {
    maKH = maKH.trim();
}



    String tongTienStr = txtTongTien.getText().trim();

    if (newMaHD.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Mã hóa đơn không được để trống!");
        return;
    }

    if (NgayLap.getDate() == null) {
        JOptionPane.showMessageDialog(this, "Vui lòng chọn ngày lập!");
        return;
    }

    Date ngay = NgayLap.getDate();
    java.sql.Date sqlDate = new java.sql.Date(ngay.getTime());

    BigDecimal tongTien;
    try {
        tongTien = new BigDecimal(tongTienStr);
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Tổng tiền không hợp lệ!");
        return;
    }

    // Nếu sửa mã hóa đơn => cần cập nhật ở cả 2 bảng
    if (!newMaHD.equals(oldMaHD)) {
        // Kiểm tra mã mới có bị trùng không
        if(hdDao.getHoaDonByMa(newMaHD) != null) {
            JOptionPane.showMessageDialog(this, "Mã hóa đơn mới đã tồn tại!");
            return;
        }

        // Cập nhật trong bảng chi tiết hóa đơn trước
        ctDao.updateMaHDCuaChiTiet(oldMaHD, newMaHD);

        // Cập nhật trong bảng hóa đơn
        hdDao.updateMaHD(oldMaHD, newMaHD);
    }

    // Cập nhật các thông tin khác
   HoaDon hd = new HoaDon(newMaHD, sqlDate, maKH, tongTien);
hdDao.updateHoaDon(hd, maKH);

    JOptionPane.showMessageDialog(this, "Sửa hóa đơn thành công!");
    loadTableHoaDon();
}
    private void bt_capnhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_capnhatActionPerformed

       suaHoaDon();
    }//GEN-LAST:event_bt_capnhatActionPerformed
       

    
    private void tbhoadonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbhoadonMouseClicked
        // TODO add your handling code here:
       int selectedRow = tbhoadon.getSelectedRow();
    if (selectedRow != -1) {
        String maHD = tbhoadon.getValueAt(selectedRow, 0).toString();
        String ngayStr = tbhoadon.getValueAt(selectedRow, 1).toString();

        // ✅ Kiểm tra null cho mã KH
        Object maKHObj = tbhoadon.getValueAt(selectedRow, 2);
        String maKH = (maKHObj == null) ? "" : maKHObj.toString();

        String tongTien = tbhoadon.getValueAt(selectedRow, 3).toString();

        txtMaHD.setText(maHD);
        txtkhachhang.setText(maKH);
        txtTongTien.setText(tongTien);

        try {
            SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
            Date ngay = sdf.parse(ngayStr);
            NgayLap.setDate(ngay);
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(this, "Lỗi định dạng ngày!");
        }

        // ✅ Click đúp để mở dialog chi tiết
        if (evt.getClickCount() == 2) {
            JDialogChiTietHoaDon dialog = new JDialogChiTietHoaDon((JFrame) SwingUtilities.getWindowAncestor(this), maHD);
            dialog.setLocationRelativeTo(this);
            dialog.setVisible(true);

            // Cập nhật lại danh sách hóa đơn
            loadTableHoaDon(); 
        }
    }
    }//GEN-LAST:event_tbhoadonMouseClicked

    private void btn_chitiethoadonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_chitiethoadonActionPerformed
        // TODO add your handling code here:
         cardLayout.show(panelContent, "qlchitiethoadon");
    }//GEN-LAST:event_btn_chitiethoadonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.JDateChooser NgayLap;
    private javax.swing.JButton bt_capnhat;
    private javax.swing.JButton bt_them;
    private javax.swing.JButton bt_xoa;
    private javax.swing.JButton btn_chitiethoadon;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbdoituong;
    private javax.swing.JTable tbhoadon;
    private javax.swing.JTextField txtMaHD;
    private javax.swing.JTextField txtTongTien;
    private javax.swing.JTextField txtkhachhang;
    private javax.swing.JTextField txttimkiem;
    // End of variables declaration//GEN-END:variables
}
